# config.yaml
defaults:
  - _self_


model:
  name: unet
  backbone: resnet34  #resnet18/34/50, resnext50_32x4d, efficientnet-b4/b5/b6
  encoder_weights: imagenet
  unfreeze: null #segmentation_head # decoder  #null
  num_classes: 2

training:
  loss: focal #focal, tversky, dice
  batch_size: 64
  lr: 0.0001
  epochs: 50
  optimizer: adam
  seed: 3407
  device: cuda
  num_workers: 4
  patience: 5
  results_path: /app/dev/FM4EO/results_cocoa/unet_res34_focal_simpletransform_13channels_lr0001_50eps

dataset:
  data_dir: /app/dev/FM4EO/data/patch_data/2016
  split_path: /app/dev/FM4EO/data/patch_data/2016/MASK/train_test_splits.csv
  classification: 'cocoa' #mining, cocoa, combined
  feature_idx: [0,1,2,3,4,5,6,7,8,9, 10,11,12] # use [2, 1, 0] for RGB
  transform: simple  # colour  # mixed # simple_norm
  

